
/*
 * Copyright (c) 1998 - 2005 Versant Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Versant Corporation - initial API and implementation
 */
package com.versant.core.jdo.junit.teststoredproc.model;

import java.util.Date;

/*
 * Generated by JDO Genie 
 */
public class Compound extends Molecule {

    private String casnumber;
    private short charge;
    private String chemicalstructure;
    private int compoundclassId;
    private String createdBy;
    private char isbiomassconstituent;
    private char isdeleted;
    private String lastModifiedBy;
    private Date lastModifiedDt;
    private String notes;
    private Molecule molecule;

    public Compound() {
    }

    public String getCasnumber() {
        return casnumber;
    }

    public void setCasnumber(String casnumber) {
        this.casnumber = casnumber;
    }

    public short getCharge() {
        return charge;
    }

    public void setCharge(short charge) {
        this.charge = charge;
    }

    public String getChemicalstructure() {
        return chemicalstructure;
    }

    public void setChemicalstructure(String chemicalstructure) {
        this.chemicalstructure = chemicalstructure;
    }

    public int getCompoundclassId() {
        return compoundclassId;
    }

    public void setCompoundclassId(int compoundclassId) {
        this.compoundclassId = compoundclassId;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public char getIsbiomassconstituent() {
        return isbiomassconstituent;
    }

    public void setIsbiomassconstituent(char isbiomassconstituent) {
        this.isbiomassconstituent = isbiomassconstituent;
    }

    public char getIsdeleted() {
        return isdeleted;
    }

    public void setIsdeleted(char isdeleted) {
        this.isdeleted = isdeleted;
    }

    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedDt() {
        return lastModifiedDt;
    }

    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }

    public String getNote() {
        return notes;
    }

    public void setNote(String notes) {
        this.notes = notes;
    }

    public Molecule getMolecule() {
        return molecule;
    }

    public void setMolecule(Molecule molecule) {
        this.molecule = molecule;
        setMoleculeId(molecule.getMoleculeId());
    }

    /**
     * Application identity objectid-class.
     */
    public static class ID implements java.io.Serializable {

        public int moleculeId;

        public ID() {
        }

        public ID(String s) {
            moleculeId = Integer.parseInt(s);
        }

        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Compound.ID)) return false;

            final Compound.ID id = (Compound.ID) o;

            if (this.moleculeId != id.moleculeId) return false;
            return true;
        }

        public int hashCode() {
            int result = 0;
            result = 29 * result + (int) moleculeId;
            return result;
        }

        public String toString() {
            StringBuffer buffer = new StringBuffer();
            buffer.append(moleculeId);
            return buffer.toString();
        }
    }
}
