
/*
 * Copyright (c) 1998 - 2005 Versant Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Versant Corporation - initial API and implementation
 */
package com.versant.core.jdo.junit.teststoredproc.model;

import java.util.Date;

/*
 * Generated by JDO Genie 
 */
public class Externalreference {

    private int externalreferenceId; // pk 
    private int clientOid;
    private String createdBy;
    private char isdeleted;
    private String lastModifiedBy;
    private Date lastModifiedDt;
    private String referenceId;
    private String tablename;
    private Externalreferencesite externalreferencesite;

    public Externalreference() {
    }

    public int getExternalreferenceId() {
        return externalreferenceId;
    }

    public void setExternalreferenceId(int externalreferenceId) {
        this.externalreferenceId = externalreferenceId;
    }

    public int getClientOid() {
        return clientOid;
    }

    public void setClientOid(int clientOid) {
        this.clientOid = clientOid;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public char getIsdeleted() {
        return isdeleted;
    }

    public void setIsdeleted(char isdeleted) {
        this.isdeleted = isdeleted;
    }

    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedDt() {
        return lastModifiedDt;
    }

    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }

    public String getReferenceId() {
        return referenceId;
    }

    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    public String getTablename() {
        return tablename;
    }

    public void setTablename(String tablename) {
        this.tablename = tablename;
    }

    public Externalreferencesite getExternalreferencesite() {
        return externalreferencesite;
    }

    public void setExternalreferencesite(Externalreferencesite externalreferencesite) {
        this.externalreferencesite = externalreferencesite;
    }

    /**
     * Application identity objectid-class.
     */
    public static class ID implements java.io.Serializable {

        public int externalreferenceId;

        public ID() {
        }

        public ID(String s) {
            externalreferenceId = Integer.parseInt(s);
        }

        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Externalreference.ID)) return false;

            final Externalreference.ID id = (Externalreference.ID) o;

            if (this.externalreferenceId != id.externalreferenceId) return false;
            return true;
        }

        public int hashCode() {
            int result = 0;
            result = 29 * result + (int) externalreferenceId;
            return result;
        }

        public String toString() {
            StringBuffer buffer = new StringBuffer();
            buffer.append(externalreferenceId);
            return buffer.toString();
        }
    }
}
