
/*
 * Copyright (c) 1998 - 2005 Versant Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Versant Corporation - initial API and implementation
 */
package com.versant.core.jdo.junit.teststoredproc.model;

import java.util.Date;

/*
 * Generated by JDO Genie 
 */
public class GcsAdmincommandparameters {
    private int admincommandparameterId;

    private String createdBy;
    private String isdeleted;
    private String lastModifiedBy;
    private Date lastModifiedDt;
    private String parameterdescription;
    private String parameterisoptional;
    private String parametername;
    private long parametersequence;
    private long parametersize;
    private String parametertype;
    private String parametervalidationcommand;
    private GcsAdmincommands gcsadmincommands;

    public GcsAdmincommandparameters() {
    }

    public int getAdmincommandparameterId() {
        return admincommandparameterId;
    }

    public void setAdmincommandparameterId(int admincommandparameterId) {
        this.admincommandparameterId = admincommandparameterId;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getIsdeleted() {
        return isdeleted;
    }

    public void setIsdeleted(String isdeleted) {
        this.isdeleted = isdeleted;
    }

    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedDt() {
        return lastModifiedDt;
    }

    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }

    public String getParameterdescription() {
        return parameterdescription;
    }

    public void setParameterdescription(String parameterdescription) {
        this.parameterdescription = parameterdescription;
    }

    public String getParameterisoptional() {
        return parameterisoptional;
    }

    public void setParameterisoptional(String parameterisoptional) {
        this.parameterisoptional = parameterisoptional;
    }

    public String getParametername() {
        return parametername;
    }

    public void setParametername(String parametername) {
        this.parametername = parametername;
    }

    public long getParametersequence() {
        return parametersequence;
    }

    public void setParametersequence(long parametersequence) {
        this.parametersequence = parametersequence;
    }

    public long getParametersize() {
        return parametersize;
    }

    public void setParametersize(long parametersize) {
        this.parametersize = parametersize;
    }

    public String getParametertype() {
        return parametertype;
    }

    public void setParametertype(String parametertype) {
        this.parametertype = parametertype;
    }

    public String getParametervalidationcommand() {
        return parametervalidationcommand;
    }

    public void setParametervalidationcommand(String parametervalidationcommand) {
        this.parametervalidationcommand = parametervalidationcommand;
    }

    public GcsAdmincommands getGcsadmincommand() {
        return gcsadmincommands;
    }

    public void setGcsadmincommand(GcsAdmincommands gcsadmincommands) {
        this.gcsadmincommands = gcsadmincommands;
    }

    /**
     * Application identity objectid-class.
     */
    public static class ID implements java.io.Serializable {

        public int admincommandparameterId;

        public ID() {
        }

        public ID(String s) {
            admincommandparameterId = Integer.parseInt(s);
        }

        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof GcsAdmincommandparameters.ID)) return false;

            final GcsAdmincommandparameters.ID id = (GcsAdmincommandparameters.ID) o;

            if (this.admincommandparameterId != id.admincommandparameterId) return false;
            return true;
        }

        public int hashCode() {
            int result = 0;
            result = 29 * result + (int) admincommandparameterId;
            return result;
        }

        public String toString() {
            StringBuffer buffer = new StringBuffer();
            buffer.append(admincommandparameterId);
            return buffer.toString();
        }
    }
}
