
/*
 * Copyright (c) 1998 - 2005 Versant Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Versant Corporation - initial API and implementation
 */
package com.versant.core.jdo.junit.teststoredproc.model;

import java.util.Date;

/*
 * Generated by JDO Genie 
 */
public class Molecule {
    public static final String REGEXP_FORMULA = "([A-Z][a-z]?[0-9]*)+";
	public static final String TYPE_PEPTIDE = "PEPTIDE";
	public static final String TYPE_PROTEIN = "PROTEIN";
	public static final String TYPE_COMPOUND = "COMPOUND";

    private long moleculeId;
    private String abbreviation;
    private String createdBy;
    private String formula;
    private String formulaneutral;
    private String formulasorted;
    private char isdeleted;
    private String lastModifiedBy;
    private Date lastModifiedDt;
    private long molecularweight;
    private int moleculenumber;
    private String moleculetype;
    private String officialname;

    public Molecule() {
    }

    public long getMoleculeId() {
        return moleculeId;
    }

    public void setMoleculeId(long moleculeId) {
        this.moleculeId = moleculeId;
    }

    public String getAbbreviation() {
        return abbreviation;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getFormula() {
        return formula;
    }

    public void setFormula(String formula) {
        this.formula = formula;
    }

    public String getFormulaneutral() {
        return formulaneutral;
    }

    public void setFormulaneutral(String formulaneutral) {
        this.formulaneutral = formulaneutral;
    }

    public String getFormulasorted() {
        return formulasorted;
    }

    public void setFormulasorted(String formulasorted) {
        this.formulasorted = formulasorted;
    }

    public char getIsdeleted() {
        return isdeleted;
    }

    public void setIsdeleted(char isdeleted) {
        this.isdeleted = isdeleted;
    }

    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedDt() {
        return lastModifiedDt;
    }

    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }

    public long getMolecularweight() {
        return molecularweight;
    }

    public void setMolecularweight(long molecularweight) {
        this.molecularweight = molecularweight;
    }

    public int getMoleculenumber() {
        return moleculenumber;
    }

    public void setMoleculenumber(int moleculenumber) {
        this.moleculenumber = moleculenumber;
    }

    public String getMoleculetype() {
        return moleculetype;
    }

    public void setMoleculetype(String moleculetype) {
        this.moleculetype = moleculetype;
    }

    public String getOfficialname() {
        return officialname;
    }

    public void setOfficialname(String officialname) {
        this.officialname = officialname;
    }

    /**
     * Application identity objectid-class.
     */
    public static class ID implements java.io.Serializable {

        public long moleculeId;

        public ID() {
        }

        public ID(String s) {
            moleculeId = Long.parseLong(s);
        }

        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Molecule.ID)) return false;

            final Molecule.ID id = (Molecule.ID) o;

            if (this.moleculeId != id.moleculeId) return false;
            return true;
        }

        public int hashCode() {
            int result = 0;
            result = 29 * result + (int) moleculeId;
            return result;
        }

        public String toString() {
            StringBuffer buffer = new StringBuffer();
            buffer.append(moleculeId);
            return buffer.toString();
        }
    }
}
