
/*
 * Copyright (c) 1998 - 2005 Versant Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Versant Corporation - initial API and implementation
 */
package com.versant.core.jdo.junit.teststoredproc.model;

import java.math.BigDecimal;
import java.util.Date;

/*
 * Generated by JDO Genie
 */
public class Reactant {

    private long reactantId; // pk
    private BigDecimal coefficient;
    private String createdBy;
    private char isdeleted;
    private char isprimary;
    private String lastModifiedBy;
    private Date lastModifiedDt;
    private char reactantrole;
    private Compartment compartment;
    private Molecule molecule;
    private Reaction reaction;

    public Reactant() {
    }

    public long getReactantId() {
        return reactantId;
    }

    public void setReactantId(long reactantId) {
        this.reactantId = reactantId;
    }

    public BigDecimal getCoefficient() {
        return coefficient;
    }

    public void setCoefficient(BigDecimal coefficient) {
        this.coefficient = coefficient;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public char getIsdeleted() {
        return isdeleted;
    }

    public void setIsdeleted(char isdeleted) {
        this.isdeleted = isdeleted;
    }

    public char getIsprimary() {
        return isprimary;
    }

    public void setIsprimary(char isprimary) {
        this.isprimary = isprimary;
    }

    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedDt() {
        return lastModifiedDt;
    }

    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }

    public char getReactantrole() {
        return reactantrole;
    }

    public void setReactantrole(char reactantrole) {
        this.reactantrole = reactantrole;
    }

    public Compartment getCompartment() {
        return compartment;
    }

    public void setCompartment(Compartment compartment) {
        this.compartment = compartment;
    }

    public Molecule getMolecule() {
        return molecule;
    }

    public void setMolecule(Molecule molecule) {
        this.molecule = molecule;
    }

    public Reaction getReaction() {
        return reaction;
    }

    public void setReaction(Reaction reaction) {
        this.reaction = reaction;
    }

    /**
     * Application identity objectid-class.
     */
    public static class ID implements java.io.Serializable {

        public long reactantId;

        public ID() {
        }

        public ID(String s) {
            reactantId = Long.parseLong(s);
        }

        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Reactant.ID)) return false;

            final Reactant.ID id = (Reactant.ID) o;

            if (this.reactantId != id.reactantId) return false;
            return true;
        }

        public int hashCode() {
            int result = 0;
            result = 29 * result + (int) reactantId;
            return result;
        }

        public String toString() {
            StringBuffer buffer = new StringBuffer();
            buffer.append(reactantId);
            return buffer.toString();
        }
    }
}
