
/*
 * Copyright (c) 1998 - 2005 Versant Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Versant Corporation - initial API and implementation
 */
package com.versant.core.jdo.junit.teststoredproc.model;

import java.util.Date;

/*
 * Generated by JDO Genie 
 */
public class Reaction {
    private long reaction_id;

    private String abbreviation;
    private String createdBy;
    private String direction;
    private String discriminator;
    private String ecnumber;
    private char enzymeclassunknown;
    private String equation;
    private String equationformula;
    private char isdeleted;
    private char issimulationreaction;
    private char istransformation;
    private char istranslocation;
    private String lastModifiedBy;
    private Date lastModifiedDt;
    private String notes;
    private String officialname;
    private int reactionnumber;
    private String sortsequence;
    private String tcnumber;
    private char transporterclassunknown;

    public Reaction() {
    }

    public long getReaction_id() {
        return reaction_id;
    }

    public String getAbbreviation() {
        return abbreviation;
    }

    public void setAbbreviation(String abbreviation) {
        this.abbreviation = abbreviation;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getDirection() {
        return direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }

    public String getDiscriminator() {
        return discriminator;
    }

    public void setDiscriminator(String discriminator) {
        this.discriminator = discriminator;
    }

    public String getEcnumber() {
        return ecnumber;
    }

    public void setEcnumber(String ecnumber) {
        this.ecnumber = ecnumber;
    }

    public char getEnzymeclassunknown() {
        return enzymeclassunknown;
    }

    public void setEnzymeclassunknown(char enzymeclassunknown) {
        this.enzymeclassunknown = enzymeclassunknown;
    }

    public String getEquation() {
        return equation;
    }

    public void setEquation(String equation) {
        this.equation = equation;
    }

    public String getEquationformula() {
        return equationformula;
    }

    public void setEquationformula(String equationformula) {
        this.equationformula = equationformula;
    }

    public char getIsdeleted() {
        return isdeleted;
    }

    public void setIsdeleted(char isdeleted) {
        this.isdeleted = isdeleted;
    }

    public char getIssimulationreaction() {
        return issimulationreaction;
    }

    public void setIssimulationreaction(char issimulationreaction) {
        this.issimulationreaction = issimulationreaction;
    }

    public char getIstransformation() {
        return istransformation;
    }

    public void setIstransformation(char istransformation) {
        this.istransformation = istransformation;
    }

    public char getIstranslocation() {
        return istranslocation;
    }

    public void setIstranslocation(char istranslocation) {
        this.istranslocation = istranslocation;
    }

    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedDt() {
        return lastModifiedDt;
    }

    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }

    public String getNote() {
        return notes;
    }

    public void setNote(String notes) {
        this.notes = notes;
    }

    public String getOfficialname() {
        return officialname;
    }

    public void setOfficialname(String officialname) {
        this.officialname = officialname;
    }

    public int getReactionnumber() {
        return reactionnumber;
    }

    public void setReactionnumber(int reactionnumber) {
        this.reactionnumber = reactionnumber;
    }

    public String getSortsequence() {
        return sortsequence;
    }

    public void setSortsequence(String sortsequence) {
        this.sortsequence = sortsequence;
    }

    public String getTcnumber() {
        return tcnumber;
    }

    public void setTcnumber(String tcnumber) {
        this.tcnumber = tcnumber;
    }

    public char getTransporterclassunknown() {
        return transporterclassunknown;
    }

    public void setTransporterclassunknown(char transporterclassunknown) {
        this.transporterclassunknown = transporterclassunknown;
    }

    /**
     * Application identity objectid-class.
     */
    public static class ID implements java.io.Serializable {
        public long reaction_id;

        public ID() {
        }

        public ID(String s) {
            reaction_id = Long.parseLong(s);
        }

        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Molecule.ID)) return false;

            final Molecule.ID id = (Molecule.ID) o;

            if (this.reaction_id != id.moleculeId) return false;
            return true;
        }

        public int hashCode() {
            int result = 0;
            result = 29 * result + (int) reaction_id;
            return result;
        }

        public String toString() {
            StringBuffer buffer = new StringBuffer();
            buffer.append(reaction_id);
            return buffer.toString();
        }
    }

}
