
/*
 * Copyright (c) 1998 - 2005 Versant Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Versant Corporation - initial API and implementation
 */
package ejb3.model;

import javax.persistence.*;

/**
 * An address.
 */
@Entity (access = AccessType.FIELD)
@Table(name = "ADDRESS")
public class Address implements java.io.Serializable {

    @Id(generate = GeneratorType.TABLE, generator = "HIGHLOW")
    @Column(name = "GEN_ID")
    private int generatedId; // this primary key is auto generated by Open Access
    private String street;
    private String city;
    private int code;

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public int getGeneratedId() {
        return generatedId;
    }

    public String toString() {
        return street + ", " + city + ", " + code;
    }

}

