
/*
 * Copyright (c) 1998 - 2005 Versant Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Versant Corporation - initial API and implementation
 */
package com.versant.core.jdo.junit.test0.model.testl2cache;

import java.util.Collection;
import java.util.Date;
import java.util.LinkedList;

/*
 * Generated by JDO Genie (version:3.2.0beta6 (05 Sep 2004))
 * 
 * WCCC pseudo biz object belonging to a Arrangement instance
 * WcccArrangement is synced from cms, ArrangementType from Res
 * ArrangementType contains convenience methods for accessing objects that are
 * in fact connected to WcccArrangement
 */

public class WcccArrangement {

    private String attentionccc;
    private String bookingchannelexception;
    private String brochure;
    private String category;
    private String conditions;
    private String contactperson;
    private String createdby;
    private Date createddate;
    private String description;
    private String descriptionccc;
    private Date enddate;
    private String externaldoctype;
    private String filename;
    private long id;
    private char isarrangement;
    private char isdeliveryservice;
    private char ishotelarrangement;
    private char isonlinebookable;
    private String location;
    private String name;
    private String nameccc;
    private String numberofpersons;
    private String organisationonvillage;
    private String path;
    private String price;
    private String reasonoffernotvalid;
    private String responsiblecontentpersonccc;
    private String responsiblecontentpersonext;
    private String sellingarguments;
    private String shortname;
    private String shortnamedisplay;
    private Date startdate;
    private String status;
    private String subtype;
    private String template;
    private String updatedby;
    private Date updateddate;
    private String urlexternaldoc;
    private String urlexternaldocxml;
    private String validarrivingperioddesc;

    public WcccArrangement() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getAttentionccc() {
        return attentionccc;
    }

    public void setAttentionccc(String attentionccc) {
        this.attentionccc = attentionccc;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getCondition() {
        return conditions;
    }

    public void setCondition(String conditions) {
        this.conditions = conditions;
    }

    public String getCreatedby() {
        return createdby;
    }

    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    public Date getCreateddate() {
        return createddate;
    }

    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescriptionccc() {
        return descriptionccc;
    }

    public void setDescriptionccc(String descriptionccc) {
        this.descriptionccc = descriptionccc;
    }

    public Date getEnddate() {
        return enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    public String getExternaldoctype() {
        return externaldoctype;
    }

    public void setExternaldoctype(String externaldoctype) {
        this.externaldoctype = externaldoctype;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNameccc() {
        return nameccc;
    }

    public void setNameccc(String nameccc) {
        this.nameccc = nameccc;
    }

    public String getOrganisationonvillage() {
        return organisationonvillage;
    }

    public void setOrganisationonvillage(String organisationonvillage) {
        this.organisationonvillage = organisationonvillage;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getReasonoffernotvalid() {
        return reasonoffernotvalid;
    }

    public void setReasonoffernotvalid(String reasonoffernotvalid) {
        this.reasonoffernotvalid = reasonoffernotvalid;
    }

    public String getSellingargument() {
        return sellingarguments;
    }

    public void setSellingargument(String sellingarguments) {
        this.sellingarguments = sellingarguments;
    }

    public String getShortname() {
        return shortname;
    }

    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    public Date getStartdate() {
        return startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    public String getStatu() {
        return status;
    }

    public void setStatu(String status) {
        this.status = status;
    }

    public String getSubtype() {
        return subtype;
    }

    public void setSubtype(String subtype) {
        this.subtype = subtype;
    }

    public String getTemplate() {
        return template;
    }

    public void setTemplate(String template) {
        this.template = template;
    }

    public String getUpdatedby() {
        return updatedby;
    }

    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    public Date getUpdateddate() {
        return updateddate;
    }

    public void setUpdateddate(Date updateddate) {
        this.updateddate = updateddate;
    }

    public String getUrlexternaldoc() {
        return urlexternaldoc;
    }

    public void setUrlexternaldoc(String urlexternaldoc) {
        this.urlexternaldoc = urlexternaldoc;
    }

    public String getUrlexternaldocxml() {
        return urlexternaldocxml;
    }

    public void setUrlexternaldocxml(String urlexternaldocxml) {
        this.urlexternaldocxml = urlexternaldocxml;
    }

    /**
     * Application identity objectid-class.
     */
    public static class ID implements java.io.Serializable {

        public long id;

        public ID() {
        }

        public ID(String s) {
            int i, p = 0;
            id = Long.parseLong(s.substring(p));
        }

        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (!(o instanceof WcccArrangement.ID)) {
                return false;
            }

            final WcccArrangement.ID id = (WcccArrangement.ID)o;

            if (this.id != id.id) {
                return false;
            }
            return true;
        }

        public int hashCode() {
            int result = 0;
            result = 29 * result + (int)(id ^ (id >>> 32));
            return result;
        }

        public String toString() {
            StringBuffer buffer = new StringBuffer();
            buffer.append(id);
            return buffer.toString();
        }
    }

    /**
     * @return
     */
    public String getConditions() {
        return conditions;
    }

    /**
     * @return
     */
    public String getSellingarguments() {
        return sellingarguments;
    }

    /**
     * @return
     */
    public String getStatus() {
        return status;
    }

    /**
     * @param string
     */
    public void setConditions(String string) {
        conditions = string;
    }

    /**
     * @param string
     */
    public void setSellingarguments(String string) {
        sellingarguments = string;
    }

    /**
     * @param string
     */
    public void setStatus(String string) {
        status = string;
    }

    private Collection wcccArrangements = new LinkedList();

    public void addWcccArrangement(WcccArrangement aWcccArrangement) {
        getWcccArrangements().add(aWcccArrangement);
    }

    /**
     * @return
     */
    public Collection getWcccArrangements() {
        return wcccArrangements;
    }

    /**
     * @param collection
     */
    public void setWcccArrangements(Collection collection) {
        wcccArrangements = collection;
    }

    /**
     * @return
     */
    public char getIsarrangement() {
        return isarrangement;
    }

    /**
     * @return
     */
    public char getIsdeliveryservice() {
        return isdeliveryservice;
    }

    /**
     * @return
     */
    public char getIshotelarrangement() {
        return ishotelarrangement;
    }

    /**
     * @return
     */
    public String getShortnamedisplay() {
        return shortnamedisplay;
    }

    /**
     * @param c
     */
    public void setIsarrangement(char c) {
        isarrangement = c;
    }

    /**
     * @param c
     */
    public void setIsdeliveryservice(char c) {
        isdeliveryservice = c;
    }

    /**
     * @param c
     */
    public void setIshotelarrangement(char c) {
        ishotelarrangement = c;
    }

    /**
     * @param string
     */
    public void setShortnamedisplay(String string) {
        shortnamedisplay = string;
    }

    private ArrangementType arrangementType;

    /**
     * @return
     */
    public ArrangementType getArrangementType() {
        return arrangementType;
    }

    /**
     * @param type
     */
    public void setArrangementType(ArrangementType type) {
        arrangementType = type;
    }

    /**
     * @return
     */
    public String getBookingchannelexception() {
        return bookingchannelexception;
    }

    /**
     * @return
     */
    public String getBrochure() {
        return brochure;
    }

    /**
     * @return
     */
    public String getContactperson() {
        return contactperson;
    }

    /**
     * @return
     */
    public char getIsonlinebookable() {
        return isonlinebookable;
    }

    /**
     * @return
     */
    public String getNumberofpersons() {
        return numberofpersons;
    }

    /**
     * @return
     */
    public String getResponsiblecontentpersonccc() {
        return responsiblecontentpersonccc;
    }

    /**
     * @return
     */
    public String getResponsiblecontentpersonext() {
        return responsiblecontentpersonext;
    }

    /**
     * @return
     */
    public String getValidarrivingperioddesc() {
        return validarrivingperioddesc;
    }

    /**
     * @param string
     */
    public void setBookingchannelexception(String string) {
        bookingchannelexception = string;
    }

    /**
     * @param string
     */
    public void setBrochure(String string) {
        brochure = string;
    }

    /**
     * @param string
     */
    public void setContactperson(String string) {
        contactperson = string;
    }

    /**
     * @param c
     */
    public void setIsonlinebookable(char c) {
        isonlinebookable = c;
    }

    /**
     * @param string
     */
    public void setNumberofpersons(String string) {
        numberofpersons = string;
    }

    /**
     * @param string
     */
    public void setResponsiblecontentpersonccc(String string) {
        responsiblecontentpersonccc = string;
    }

    /**
     * @param string
     */
    public void setResponsiblecontentpersonext(String string) {
        responsiblecontentpersonext = string;
    }

    /**
     * @param string
     */
    public void setValidarrivingperioddesc(String string) {
        validarrivingperioddesc = string;
    }

}
