
/*
 * Copyright (c) 1998 - 2005 Versant Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Versant Corporation - initial API and implementation
 */
package storedprocs.model;

import java.util.Date;

/*
 * Generated by JDO Genie 
 */
public class Compartment {

    private long compartmentId; // pk
    private char abbreviation;
    private String createdBy;
    private String description;
    private char isdeleted;
    private String lastModifiedBy;
    private Date lastModifiedDt;

    public Compartment() {
    }

    public long getCompartmentId() {
        return compartmentId;
    }

    public void setCompartmentId(long compartmentId) {
        this.compartmentId = compartmentId;
    }

    public char getAbbreviation() {
        return abbreviation;
    }

    public void setAbbreviation(char abbreviation) {
        this.abbreviation = abbreviation;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public char getIsdeleted() {
        return isdeleted;
    }

    public void setIsdeleted(char isdeleted) {
        this.isdeleted = isdeleted;
    }

    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedDt() {
        return lastModifiedDt;
    }

    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }

    /**
     * Application identity objectid-class.
     */
    public static class ID implements java.io.Serializable {

        public long compartmentId;

        public ID() {
        }

        public ID(String s) {
            compartmentId = Long.parseLong(s);
        }

        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Compartment.ID)) return false;

            final Compartment.ID id = (Compartment.ID) o;

            if (this.compartmentId != id.compartmentId) return false;
            return true;
        }

        public int hashCode() {
            int result = 0;
            result = 29 * result + (int) compartmentId;
            return result;
        }

        public String toString() {
            StringBuffer buffer = new StringBuffer();
            buffer.append(compartmentId);
            return buffer.toString();
        }
    }
}
