
/*
 * Copyright (c) 1998 - 2005 Versant Corporation
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 * Versant Corporation - initial API and implementation
 */
package storedprocs.model;

import java.util.Date;

/*
 * Generated by JDO Genie 
 */
public class Externalreferencesite {

    private int externalreferencesiteId; // pk 
    private String createdBy;
    private String description;
    private char isdeleted;
    private char isdynamic;
    private String lastModifiedBy;
    private Date lastModifiedDt;
    private String name;
    private String urlstring;

    public Externalreferencesite() {
    }

    public int getExternalreferencesiteId() {
        return externalreferencesiteId;
    }

    public void setExternalreferencesiteId(int externalreferencesiteId) {
        this.externalreferencesiteId = externalreferencesiteId;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public char getIsdeleted() {
        return isdeleted;
    }

    public void setIsdeleted(char isdeleted) {
        this.isdeleted = isdeleted;
    }

    public char getIsdynamic() {
        return isdynamic;
    }

    public void setIsdynamic(char isdynamic) {
        this.isdynamic = isdynamic;
    }

    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedDt() {
        return lastModifiedDt;
    }

    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrlstring() {
        return urlstring;
    }

    public void setUrlstring(String urlstring) {
        this.urlstring = urlstring;
    }

    /**
     * Application identity objectid-class.
     */
    public static class ID implements java.io.Serializable {

        public int externalreferencesiteId;

        public ID() {
        }

        public ID(String s) {
            externalreferencesiteId = Integer.parseInt(s);
        }

        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Externalreferencesite.ID)) return false;

            final Externalreferencesite.ID id = (Externalreferencesite.ID) o;

            if (this.externalreferencesiteId != id.externalreferencesiteId) return false;
            return true;
        }

        public int hashCode() {
            int result = 0;
            result = 29 * result + (int) externalreferencesiteId;
            return result;
        }

        public String toString() {
            StringBuffer buffer = new StringBuffer();
            buffer.append(externalreferencesiteId);
            return buffer.toString();
        }
    }
}
